import AudioLinkCore
import Foundation

public enum SignalPathMeasurementMode: String, Codable, CaseIterable, Sendable { case continuousCapture, scheduledWindow, repeatedMarker, offlineFileRoundTrip }
public enum SignalPathNodeKind: String, Codable, CaseIterable, Sendable { case sourceDevice, destinationDevice, externalApplication, pluginChain, virtualDevice, physicalProcessor, unknown }
public struct SignalPathNode: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let name: String; public let kind: SignalPathNodeKind; public let deviceUID: String?; public let channel: Int?; public init(id: UUID = UUID(), name: String, kind: SignalPathNodeKind, deviceUID: String? = nil, channel: Int? = nil) { self.id = id; self.name = name; self.kind = kind; self.deviceUID = deviceUID; self.channel = channel } }
public struct SignalPathConnection: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let from: UUID; public let to: UUID; public let notes: String?; public init(id: UUID = UUID(), from: UUID, to: UUID, notes: String? = nil) { self.id = id; self.from = from; self.to = to; self.notes = notes } }
public struct ExternalApplicationDescriptor: Codable, Equatable, Sendable { public let name: String; public let version: String?; public let isAutomaticallyInspectable: Bool; public init(name: String, version: String? = nil, isAutomaticallyInspectable: Bool = false) { self.name = name; self.version = version; self.isAutomaticallyInspectable = isAutomaticallyInspectable } }
public struct ManualRoutingInstruction: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let order: Int; public let instruction: String; public init(id: UUID = UUID(), order: Int, instruction: String) { self.id = id; self.order = order; self.instruction = instruction } }
public struct SignalPathConfiguration: Codable, Equatable, Sendable { public let mode: SignalPathMeasurementMode; public let sampleRate: SampleRate; public let timeout: DurationSeconds; public let expectedDelayRange: SampleLagRange?; public let markerVersion: String; public let instructions: [ManualRoutingInstruction]; public init(mode: SignalPathMeasurementMode, sampleRate: SampleRate, timeout: DurationSeconds = .oneTenthSecond, expectedDelayRange: SampleLagRange? = nil, markerVersion: String = "1", instructions: [ManualRoutingInstruction] = []) { self.mode = mode; self.sampleRate = sampleRate; self.timeout = timeout; self.expectedDelayRange = expectedDelayRange; self.markerVersion = markerVersion; self.instructions = instructions } }
public struct SignalPathSession: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let createdAt: Date; public let nodes: [SignalPathNode]; public let connections: [SignalPathConnection]; public let configuration: SignalPathConfiguration; public init(id: UUID = UUID(), createdAt: Date = Date(), nodes: [SignalPathNode], connections: [SignalPathConnection], configuration: SignalPathConfiguration) { self.id = id; self.createdAt = createdAt; self.nodes = nodes; self.connections = connections; self.configuration = configuration } }
public struct RoutingCheckpoint: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let name: String; public let expectedSampleOffset: Int?; public let detectedSampleOffset: Int?; public let found: Bool; public init(id: UUID = UUID(), name: String, expectedSampleOffset: Int? = nil, detectedSampleOffset: Int? = nil, found: Bool) { self.id = id; self.name = name; self.expectedSampleOffset = expectedSampleOffset; self.detectedSampleOffset = detectedSampleOffset; self.found = found } }
public struct PathUncertainty: Codable, Equatable, Sendable { public let standardDeviationFrames: Double?; public let reasons: [String]; public init(standardDeviationFrames: Double? = nil, reasons: [String] = []) { self.standardDeviationFrames = standardDeviationFrames; self.reasons = reasons } }
public struct PathMeasurementResult: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let sessionID: UUID; public let measuredDelayFrames: Double?; public let sampleRate: SampleRate; public let checkpoints: [RoutingCheckpoint]; public let uncertainty: PathUncertainty; public let warnings: [String]; public let observedChannelMapping: String?; public let polarityInverted: Bool?; public let sampleRateConverted: Bool; public let completedAt: Date; public init(id: UUID = UUID(), sessionID: UUID, measuredDelayFrames: Double?, sampleRate: SampleRate, checkpoints: [RoutingCheckpoint], uncertainty: PathUncertainty = .init(), warnings: [String] = [], observedChannelMapping: String? = nil, polarityInverted: Bool? = nil, sampleRateConverted: Bool = false, completedAt: Date = Date()) { self.id = id; self.sessionID = sessionID; self.measuredDelayFrames = measuredDelayFrames; self.sampleRate = sampleRate; self.checkpoints = checkpoints; self.uncertainty = uncertainty; self.warnings = warnings; self.observedChannelMapping = observedChannelMapping; self.polarityInverted = polarityInverted; self.sampleRateConverted = sampleRateConverted; self.completedAt = completedAt } }
public struct SignalPathTemplate: Codable, Equatable, Identifiable, Sendable { public let id: UUID; public let name: String; public let session: SignalPathSession; public init(id: UUID = UUID(), name: String, session: SignalPathSession) { self.id = id; self.name = name; self.session = session } }
public struct PathComparison: Codable, Equatable, Sendable { public let left: PathMeasurementResult; public let right: PathMeasurementResult; public let delayDifferenceFrames: Double?; public let warnings: [String]; public init(left: PathMeasurementResult, right: PathMeasurementResult) { self.left = left; self.right = right; self.delayDifferenceFrames = left.measuredDelayFrames.flatMap { l in right.measuredDelayFrames.map { l - $0 } }; var issues: [String] = []; if left.sampleRate != right.sampleRate { issues.append("sampleRate differs") }; self.warnings = issues } }

public enum SignalPathMarkerKind: String, Codable, CaseIterable, Sendable { case sessionStart, calibration, main, timing, sessionEnd }
public struct SignalPathMarker: Codable, Equatable, Sendable { public let kind: SignalPathMarkerKind; public let version: String; public let sessionID: UUID; public let sequence: Int; public let samples: [Float]; public init(kind: SignalPathMarkerKind, version: String, sessionID: UUID, sequence: Int, samples: [Float]) { self.kind = kind; self.version = version; self.sessionID = sessionID; self.sequence = sequence; self.samples = samples } }
public struct SignalPathMarkerDetection: Codable, Equatable, Sendable { public let marker: SignalPathMarkerKind; public let sampleOffset: Int?; public let correlation: Double; public let found: Bool; public let versionMatches: Bool; public init(marker: SignalPathMarkerKind, sampleOffset: Int?, correlation: Double, found: Bool, versionMatches: Bool) { self.marker = marker; self.sampleOffset = sampleOffset; self.correlation = correlation; self.found = found; self.versionMatches = versionMatches } }
